/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message-input.component.ngfactory';
import * as i2 from './message-input.component';
import * as i3 from './message.service';
import * as i4 from './message-list.component.ngfactory';
import * as i5 from './message-list.component';
import * as i6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n                '])),(_l()(),i0.ɵeld(2,
          0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),
          (null as any),(null as any),i1.View_MessageInputComponent_0,i1.RenderType_MessageInputComponent)),
      i0.ɵdid(3,114688,(null as any),0,i2.MessageInputComponent,[i3.MessageService],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(6,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),
      (_l()(),i0.ɵeld(8,0,(null as any),(null as any),4,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
          (null as any),['\n                '])),(_l()(),i0.ɵeld(10,0,(null as any),
          (null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_MessageListComponent_0,i4.RenderType_MessageListComponent)),
      i0.ɵdid(11,114688,(null as any),0,i5.MessageListComponent,[i3.MessageService],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],
      (_ck,_v) => {
        _ck(_v,3,0);
        _ck(_v,11,0);
      },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i0.ɵdid(1,114688,(null as any),0,i6.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessagesComponentNgFactory:i0.ComponentFactory<i6.MessagesComponent> = i0.ɵccf('app-messages',
    i6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9wZWFyc29uZC9Eb2N1bWVudHMvQW5ndWxhci91ZGVteS1jb3Vyc2VzL21lYW4tc3RhY2svc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgICAgICA8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDxocj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgICAgICA8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+XG4gICAgPC9kaXY+IiwiPGFwcC1tZXNzYWdlcz48L2FwcC1tZXNzYWdlcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBaUIsMERBQ0Q7VUFBQTtVQUFBO2FBQUE7VUFBQSw2QkFBdUM7TUFDakMsc0RBQ1Y7VUFBQTtVQUFBLDhCQUFJO01BQ0o7VUFBQSwwREFBaUI7VUFBQSx1Q0FDYjtVQUFBO1VBQUE7YUFBQTtVQUFBLDZCQUFxQzs7UUFKckM7UUFJQTs7OztvQkNMaEI7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
