/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message.component.ngfactory';
import * as i2 from './message.component';
import * as i3 from './message.service';
import * as i4 from '@angular/common';
import * as i5 from './message-list.component';
const styles_MessageListComponent:any[] = ([] as any[]);
export const RenderType_MessageListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessageListComponent,data:{}});
function View_MessageListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),2,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_MessageComponent_0,
      i1.RenderType_MessageComponent)),i0.ɵdid(1,49152,(null as any),0,i2.MessageComponent,
      [i3.MessageService],{message:[0,'message']},(null as any)),(_l()(),i0.ɵted(-1,
      (null as any),['\n            ']))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_MessageListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
      (null as any),1,(null as any),View_MessageListComponent_1)),i0.ɵdid(4,802816,
      (null as any),0,i4.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
      {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i5.MessageListComponent = _v.component;
    const currVal_0:any = _co.messages;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_MessageListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-message-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessageListComponent_0,
      RenderType_MessageListComponent)),i0.ɵdid(1,114688,(null as any),0,i5.MessageListComponent,
      [i3.MessageService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessageListComponentNgFactory:i0.ComponentFactory<i5.MessageListComponent> = i0.ɵccf('app-message-list',
    i5.MessageListComponent,View_MessageListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9wZWFyc29uZC9Eb2N1bWVudHMvQW5ndWxhci91ZGVteS1jb3Vyc2VzL21lYW4tc3RhY2svc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcGVhcnNvbmQvRG9jdW1lbnRzL0FuZ3VsYXIvdWRlbXktY291cnNlcy9tZWFuLXN0YWNrL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQudHMuTWVzc2FnZUxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgPGFwcC1tZXNzYWdlIFttZXNzYWdlXT1cIm1lc3NhZ2VcIiAqbmdGb3I9XCJsZXQgbWVzc2FnZSBvZiBtZXNzYWdlc1wiPlxuICAgICAgICAgICAgPC9hcHAtbWVzc2FnZT5cbiAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0VJO01BQUE7b0NBQUEsVUFBQTtNQUFBLDJEQUFrRTtNQUFBO0lBQXJEO0lBQWIsV0FBYSxTQUFiOzs7O29CQUZKLDhDQUNJO01BQUE7TUFBQSx3RUFBc0M7YUFBQSwrQkFDdEM7TUFBQSxtRUFBQTtNQUFBO01BQUEsdUNBQ3NCO01BQ2hCOztJQUYyQjtJQUFqQyxXQUFpQyxTQUFqQzs7OztvQkNGSjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
